// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.27.0
// source: internal/protos/config.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcTopic string `protobuf:"bytes,1,opt,name=src_topic,json=srcTopic,proto3" json:"src_topic,omitempty"`
	DstTable string `protobuf:"bytes,2,opt,name=dst_table,json=dstTable,proto3" json:"dst_table,omitempty"`
}

func (x *Stream) Reset() {
	*x = Stream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_internal_protos_config_proto_rawDescGZIP(), []int{0}
}

func (x *Stream) GetSrcTopic() string {
	if x != nil {
		return x.SrcTopic
	}
	return ""
}

func (x *Stream) GetDstTable() string {
	if x != nil {
		return x.DstTable
	}
	return ""
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcConnectionString string    `protobuf:"bytes,1,opt,name=src_connection_string,json=srcConnectionString,proto3" json:"src_connection_string,omitempty"`
	DstConnectionString string    `protobuf:"bytes,2,opt,name=dst_connection_string,json=dstConnectionString,proto3" json:"dst_connection_string,omitempty"`
	Streams             []*Stream `protobuf:"bytes,3,rep,name=streams,proto3" json:"streams,omitempty"`
	StateTable          string    `protobuf:"bytes,4,opt,name=state_table,json=stateTable,proto3" json:"state_table,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_internal_protos_config_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetSrcConnectionString() string {
	if x != nil {
		return x.SrcConnectionString
	}
	return ""
}

func (x *Config) GetDstConnectionString() string {
	if x != nil {
		return x.DstConnectionString
	}
	return ""
}

func (x *Config) GetStreams() []*Stream {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *Config) GetStateTable() string {
	if x != nil {
		return x.StateTable
	}
	return ""
}

var File_internal_protos_config_proto protoreflect.FileDescriptor

var file_internal_protos_config_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x61, 0x61, 0x72, 0x64, 0x61, 0x70, 0x70, 0x65, 0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x22, 0x42, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x72,
	0x63, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x72, 0x63, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x73, 0x74, 0x5f, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x73, 0x74, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x22, 0xc5, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x32, 0x0a, 0x15, 0x73, 0x72, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13,
	0x73, 0x72, 0x63, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x12, 0x32, 0x0a, 0x15, 0x64, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x13, 0x64, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x32, 0x0a, 0x07, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x61, 0x72, 0x64, 0x61,
	0x70, 0x70, 0x65, 0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x07, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x39, 0x5a, 0x37,
	0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x64, 0x63, 0x68, 0x65, 0x72, 0x65, 0x64, 0x6e, 0x69, 0x6b, 0x2f, 0x41, 0x61,
	0x72, 0x64, 0x61, 0x70, 0x70, 0x65, 0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_protos_config_proto_rawDescOnce sync.Once
	file_internal_protos_config_proto_rawDescData = file_internal_protos_config_proto_rawDesc
)

func file_internal_protos_config_proto_rawDescGZIP() []byte {
	file_internal_protos_config_proto_rawDescOnce.Do(func() {
		file_internal_protos_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protos_config_proto_rawDescData)
	})
	return file_internal_protos_config_proto_rawDescData
}

var file_internal_protos_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_protos_config_proto_goTypes = []interface{}{
	(*Stream)(nil), // 0: aardappel_config.Stream
	(*Config)(nil), // 1: aardappel_config.Config
}
var file_internal_protos_config_proto_depIdxs = []int32{
	0, // 0: aardappel_config.Config.streams:type_name -> aardappel_config.Stream
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_protos_config_proto_init() }
func file_internal_protos_config_proto_init() {
	if File_internal_protos_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_protos_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protos_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protos_config_proto_goTypes,
		DependencyIndexes: file_internal_protos_config_proto_depIdxs,
		MessageInfos:      file_internal_protos_config_proto_msgTypes,
	}.Build()
	File_internal_protos_config_proto = out.File
	file_internal_protos_config_proto_rawDesc = nil
	file_internal_protos_config_proto_goTypes = nil
	file_internal_protos_config_proto_depIdxs = nil
}
